name: Auto Deployment to Github Pages

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    # ----------------------------------------------------Ruby
    - name: Install Ruby
      uses: actions/setup-ruby@v1
      with:
        version: 2.6.x
    - name: Ruby Version
      run: |
        ruby -v
    - name: Setup Ruby Dependencies
      run: |
        gem update bundler
        bundle install --jobs 4 --retry 3
    - name: Test Ruby Dependencies
      run: |
        bundle exec rake -T
    # ----------------------------------------------------Webpack
    - name: Build Webpack File
      run: |
        bundle exec rake webpack:build:production
    - name: Build Middle Site
      run: |
        export TERM=xterm
        bundle exec middleman build -e production --verbose
    # ----------------------------------------------------Deploy
    - name: Deploy to Github Pages
      uses: peaceiris/actions-gh-pages@v1.1.0
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./build
